### ISSUE TITLE
Possible bug in Naiveical.Modificator.insert_into/3 or Naiveical.Modificator.insert_into/4 

### ISSUE THREAD

**Issue by DimitrijeDimitrijevic** [MigaduMail/naiveical#3]
I was playing around with examples from readme.md, and noticed that when trying to insert VTODO in VCALENDAR, it is inserting something like 
> BEGIN:VCALENDAR
calendar stuff
BEGIN:VCALENDAR
calendar stuff
BEGIN:VTODO
todo stuff
END:VTODO
END:VCALENDAR
END:VCALENDAR

Need review of what is happening.

**Comment by swerter** [comment]
Oups, that is not good.
